# Site
title:              OpenCon Cascadia
bio:                ''
description:        "The Pacific Northwest OpenCon"
locale:             en_US
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Page-gen for team members
page_gen:
- data: 'members'
  template: 'person'
  name: 'name'
  dir: 'team'

# Jekyll
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Social
# twitter:           OpenConCascadia19
github:             OpenCon-Cascadia

# personal
location:           Portland, OR, USA
email:              openconcascadia@gmail.com 

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
